### ISSUE TITLE
Validate AC by Let's Encrypt

### ISSUE THREAD

**Issue by fabianoflorentino** [fabianoflorentino/certificate-validate#1]
Error on validate certificates Let's Encrypt

```shell
Traceback (most recent call last):
  File "/certificate/certificate.py", line 179, in <module>
    print(print_basic_info(hostinfo))
  File "/certificate/certificate.py", line 146, in print_basic_info
    "crl": f'{get_crl(host_basic_info.cert)}',
  File "/certificate/certificate.py", line 80, in get_crl
    ext = cert.extensions.get_extension_for_oid(
  File "/home/python/.local/lib/python3.9/site-packages/cryptography/x509/extensions.py", line 121, in get_extension_for_oid
    raise ExtensionNotFound("No {} extension was found".format(oid), oid)
cryptography.x509.extensions.ExtensionNotFound: No <ObjectIdentifier(oid=2.5.29.31, name=cRLDistributionPoints)> extension was found
```

**Comment by fabianoflorentino** [comment]
AC Let's Encrypt Certificate Validation Workaround
